highlighter: rouge
markdown: kramdown
exclude: ["README.md"]
url: https://stevetotheizz0.github.io
baseurl: /decktech_archives
gems: [jekyll-paginate]
plugins_dir: [jekyll-paginate]
paginate: 30
paginate_path: "page:num"
